# Generated by Django 5.0 on 2024-06-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0032_alter_payroll_leave_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_data',
            name='personal_mail_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
